/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package log;

import com.sun.jndi.cosnaming.IiopUrl;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author 7_amdi
 */
public class Patient_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Patient_Bill
     */
    Connection con=null;
     PreparedStatement pst=null;
     ResultSet rest=null;
    public Patient_Bill() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
      this.setResizable(false);
      con=conn.connect();
      this.tabel();
    }

    
    
    
    
    
    
    
     public void tabel(){
    try{
    String select="SELECT * FROM hospital.patient_bill";
    pst=con.prepareStatement(select);
    rest=pst.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rest));
    
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e);
    }
    finally{ 
        try {
            rest.close();
        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addrees = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        idbill = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        costs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 44, 60, 40);
        jPanel1.add(id);
        id.setBounds(100, 50, 160, 40);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(120, 100, 240, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 100, 90, 40);

        addrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreesActionPerformed(evt);
            }
        });
        jPanel1.add(addrees);
        addrees.setBounds(180, 150, 240, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 150, 90, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 210, 90, 40);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(220, 210, 240, 40);

        idbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbillActionPerformed(evt);
            }
        });
        jPanel1.add(idbill);
        idbill.setBounds(280, 270, 240, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ID_Bill:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 270, 90, 40);

        costs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costsActionPerformed(evt);
            }
        });
        jPanel1.add(costs);
        costs.setBounds(290, 340, 240, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cost :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 340, 90, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(650, 10, 320, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\7_amdi\\Downloads\\New Folder\\search-button-icon.png")); // NOI18N
        jLabel8.setText("Search ID :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 10, 120, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Address", "Phone", "ID_Bill", "Costs", "Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(560, 70, 452, 402);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/Button-Add-icon.png"))); // NOI18N
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(30, 540, 180, 70);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/Actions-edit-redo-icon.png000.png"))); // NOI18N
        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(240, 540, 190, 70);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/Button-Close-icon.png"))); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(450, 540, 180, 70);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/Go-back-icon.png"))); // NOI18N
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(650, 540, 160, 70);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(830, 540, 160, 70);

        bac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/doc pat.jpg"))); // NOI18N
        jPanel1.add(bac);
        bac.setBounds(0, 0, 1050, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addreesActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void idbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbillActionPerformed

    private void costsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costsActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased

        if(jTextField5.getText().equals("")){
            this.tabel();
            id.setText("");
            addrees.setText("");
            phone.setText("");
            costs.setText("");
            idbill.setText("");
            name.setText("");
        }
        else
        try{
            String scan="select *  FROM hospital.patient_bill where ID=?";
            pst=con.prepareStatement(scan);
            pst.setString(1, jTextField5.getText());

            rest =pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rest));

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        finally{
            try {
                rest.close();
            } catch (SQLException ex) {
                Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);

            }
            //  this.tabel();
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try{
            int row =jTable1.getSelectedRow();
            String clk=(jTable1.getModel().getValueAt(row, 0).toString());
            String excut="SELECT * FROM hospital.patient_bill where ID='"+clk+"'";
            pst=con.prepareStatement(excut);
            rest=pst.executeQuery();
            if(rest.next())
            {String add=rest.getString("ID");
                id.setText(add);
                String add1=rest.getString("Address");
                addrees.setText(add1);
                String add2=rest.getString("Phone");
                phone.setText(add2);
                String add3=rest.getString("ID_Bill");
                idbill.setText(add3);
                String add4=rest.getString("Costs");
                costs.setText(add4);
                String add5=rest.getString("Name");
                name.setText(add5);
            }

        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        try{
            String Add="INSERT INTO `hospital`.`patient_bill` (`ID`, `Address`,`Phone`,`ID_Bill` ,`Costs`,`Name`) VALUES('"+id.getText()+ "' , '"+addrees.getText()+ "','"+phone.getText()+ "','"+idbill.getText()+"','"+costs.getText()+"','"+name.getText()+"')";
            pst =con.prepareStatement(Add);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Done");
            id.setText("");
            addrees.setText("");
            phone.setText("");
            costs.setText("");
            idbill.setText("");
            name.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);

        }
        finally {
            try {
                pst.close();
            } catch (SQLException ex) {

            }
            finally{
                try {
                    rest.close();
                } catch (SQLException ex) {
                    Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            String updat="update hospital.patient_bill set ID=?, Address=? ,phone=?,ID_Bill=?,Costs=?, Name=? where ID='"+id.getText()+"';";
            pst=con.prepareStatement(updat);
            pst.setString(1, id.getText());
            pst.setString(2, addrees.getText());
            pst.setString(3, phone.getText());
             pst.setString(4, idbill.getText());
              pst.setString(5, costs.getText());
              pst.setString(6, name.getText());
            pst.execute();
           id.setText("");
            addrees.setText("");
            phone.setText("");
            costs.setText("");
            idbill.setText("");
           name.setText("");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        finally{
            try {
                rest.close();
            } catch (SQLException ex) {
                Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);

            }
            this.tabel();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        try{
            String del="delete from hospital.patient_bill where ID=?";
            pst=con.prepareStatement(del);
            pst.setString(1, id.getText());

            pst.execute();
           id.setText("");
            addrees.setText("");
            phone.setText("");
            costs.setText("");
            idbill.setText("");
           name.setText("");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        finally{
            try {
                rest.close();
            } catch (SQLException ex) {
                Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);

            }
            this.tabel();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        new form3().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrees;
    private javax.swing.JLabel bac;
    private javax.swing.JTextField costs;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idbill;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
